name: build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          - "4.14"
          - "5.2"
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: ocaml/setup-ocaml@v3
      with:
        ocaml-compiler: ${{ matrix.ocaml-compiler }}
    - run: opam install -y dune
    - run: opam exec -- dune build
    - run: opam exec -- dune exec src/hello.exe
